#!/usr/bin/env python3
"""Generate TurboQuant codebook tables as C++ constexpr arrays.

One-time dev script. Run this, copy the output into server-turboquant.cpp.
Uses the same Beta-distribution math as turboquant.py reference impl.

Usage:
    python training/scripts/generate_turboquant_tables.py
"""

import numpy as np
from scipy.special import betaincinv
from scipy.stats import beta as beta_dist


def compute_codebook(dim: int, bits: int) -> tuple[list[float], list[float]]:
    """Compute Beta((d-1)/2, (d-1)/2) optimal codebook.

    Returns (boundaries, centroids) for scalar quantization of
    coordinates after random orthogonal rotation.
    """
    n_centroids = 1 << bits
    a = b = (dim - 1) / 2.0

    # Equal-probability quantile boundaries on [0, 1]
    quantiles = np.array([i / n_centroids for i in range(1, n_centroids)])
    boundaries_01 = betaincinv(a, b, quantiles)

    # Map from [0,1] to [-1,1]: x = 2*p - 1
    boundaries = 2.0 * boundaries_01 - 1.0

    # Compute centroids as conditional expectations E[X | lower <= X <= upper]
    n_points = 2000
    centroids = []
    edges = np.concatenate([[-1.0], boundaries, [1.0]])

    for i in range(n_centroids):
        lo, hi = edges[i], edges[i + 1]
        x = np.linspace(lo, hi, n_points)

        # Beta PDF on [-1,1]: scale from [0,1] Beta
        x01 = (x + 1) / 2
        pdf = beta_dist.pdf(x01, a, b) / 2  # Jacobian for [-1,1]

        numerator = np.trapezoid(x * pdf, x)
        denominator = np.trapezoid(pdf, x)

        centroid = numerator / denominator if denominator > 1e-15 else (lo + hi) / 2
        centroids.append(centroid)

    return boundaries.tolist(), centroids


def format_cpp_array(name: str, values: list[float]) -> str:
    """Format as C++ constexpr array."""
    vals = ", ".join(f"{v:.10f}f" for v in values)
    return f"static constexpr float {name}[] = {{{vals}}};"


def main():
    configs = [
        (128, 3),
        (128, 4),
        (256, 3),
        (256, 4),
        (512, 3),
        (512, 4),
    ]

    print("// Auto-generated by training/scripts/generate_turboquant_tables.py")
    print("// Do not edit manually.")
    print()

    for dim, bits in configs:
        boundaries, centroids = compute_codebook(dim, bits)
        n = 1 << bits

        tag = f"d{dim}_b{bits}"
        print(f"// dim={dim}, bits={bits}, n_centroids={n}")
        print(format_cpp_array(f"tq_boundaries_{tag}", boundaries))
        print(format_cpp_array(f"tq_centroids_{tag}", centroids))
        print()

    # Print a lookup helper
    print("// Lookup helper: returns (boundaries, centroids, n_centroids) for (dim, bits)")
    print("static const float * tq_get_boundaries(uint32_t dim, uint8_t bits) {")
    for dim, bits in configs:
        print(f"    if (dim == {dim} && bits == {bits}) return tq_boundaries_d{dim}_b{bits};")
    print("    return nullptr;")
    print("}")
    print()
    print("static const float * tq_get_centroids(uint32_t dim, uint8_t bits) {")
    for dim, bits in configs:
        print(f"    if (dim == {dim} && bits == {bits}) return tq_centroids_d{dim}_b{bits};")
    print("    return nullptr;")
    print("}")
    print()
    print("static uint32_t tq_get_n_centroids(uint8_t bits) {")
    print("    return 1u << bits;")
    print("}")


if __name__ == "__main__":
    main()
